// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaObUGI5fgMvQG4dvT0MGinY4_kYkv99M',
    appId: '1:524988152487:web:2de46ed0a33301dff03982',
    messagingSenderId: '524988152487',
    projectId: 'mobile-final-project-33460',
    authDomain: 'mobile-final-project-33460.firebaseapp.com',
    storageBucket: 'mobile-final-project-33460.firebasestorage.app',
    measurementId: 'G-WT0L31RPQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN_RjPS5SvJlKjjMbW9sqA8kd8aGjTOvI',
    appId: '1:524988152487:android:ffa4ba18a99cbc4ff03982',
    messagingSenderId: '524988152487',
    projectId: 'mobile-final-project-33460',
    storageBucket: 'mobile-final-project-33460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaYo6dhg8x9IhdrDyPQXIhbslFo6kHEus',
    appId: '1:524988152487:ios:938c2c3ddc2a7541f03982',
    messagingSenderId: '524988152487',
    projectId: 'mobile-final-project-33460',
    storageBucket: 'mobile-final-project-33460.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaYo6dhg8x9IhdrDyPQXIhbslFo6kHEus',
    appId: '1:524988152487:ios:938c2c3ddc2a7541f03982',
    messagingSenderId: '524988152487',
    projectId: 'mobile-final-project-33460',
    storageBucket: 'mobile-final-project-33460.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaObUGI5fgMvQG4dvT0MGinY4_kYkv99M',
    appId: '1:524988152487:web:f2827d00e71efff0f03982',
    messagingSenderId: '524988152487',
    projectId: 'mobile-final-project-33460',
    authDomain: 'mobile-final-project-33460.firebaseapp.com',
    storageBucket: 'mobile-final-project-33460.firebasestorage.app',
    measurementId: 'G-RJDL6J6DTF',
  );
}
