// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZsduHlzvEV3eQ59FoNSbRHL3fgeoiYWo',
    appId: '1:223384691553:web:5971b3f6c132e498fc9b20',
    messagingSenderId: '223384691553',
    projectId: 'ma-project-1dae3',
    authDomain: 'ma-project-1dae3.firebaseapp.com',
    databaseURL: 'https://ma-project-1dae3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ma-project-1dae3.firebasestorage.app',
    measurementId: 'G-P9G8Z8PFVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMImSS7cuamKztmzUzhk6LvkaUc9ydROQ',
    appId: '1:223384691553:android:4530394fe864e3e6fc9b20',
    messagingSenderId: '223384691553',
    projectId: 'ma-project-1dae3',
    databaseURL: 'https://ma-project-1dae3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ma-project-1dae3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-pYLk8h4ikjrz9pBz65AVRzOqCKlD5qM',
    appId: '1:223384691553:ios:d2cc330042bea795fc9b20',
    messagingSenderId: '223384691553',
    projectId: 'ma-project-1dae3',
    databaseURL: 'https://ma-project-1dae3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ma-project-1dae3.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-pYLk8h4ikjrz9pBz65AVRzOqCKlD5qM',
    appId: '1:223384691553:ios:d2cc330042bea795fc9b20',
    messagingSenderId: '223384691553',
    projectId: 'ma-project-1dae3',
    databaseURL: 'https://ma-project-1dae3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ma-project-1dae3.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZsduHlzvEV3eQ59FoNSbRHL3fgeoiYWo',
    appId: '1:223384691553:web:744e62f188035428fc9b20',
    messagingSenderId: '223384691553',
    projectId: 'ma-project-1dae3',
    authDomain: 'ma-project-1dae3.firebaseapp.com',
    databaseURL: 'https://ma-project-1dae3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ma-project-1dae3.firebasestorage.app',
    measurementId: 'G-2TRJFLJ1TX',
  );
}
